name: MineStead
version: ${version}
main: me.lyamray.minestead.MineStead
api-version: '1.21'
load: STARTUP
authors: [ LyamRay ]
description: Create your own homestead in minecraft!
website: https://github.com/LyamRay
depend: [FancyNpcs]
commands:
  resettut:
    description: Test command for resetting the players tutorial!